<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegisterLink</name>
   <tag></tag>
   <elementGuidId>fdc5addf-9c07-4c0e-8f47-d467f7da1083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p/a[text()='Register']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
